$ANSIBLE_VAULT;1.1;AES256
62633535653761366633626434353063386537393134346365373232363631366433636336653230
6365323662316238383830373437333336383562376634350a616161306332643066326438653063
63303966326163643530653762353434353634383263356333383861623935646165636664333235
6563623232343139620a363964363134353161353265303365366538363836383934316463663733
38613034666132656164303166613561663732663338653866393633303136393233356532636162
37623131303564343231366363663734303034303132316535623132333639616461373133643766
34376365633135336638643664656338363765643939323061353235663765366264303638656161
36303231323637633561616263633833666434383534616665663037333431303161663437663938
30396633333961376435333131646131393133633932346266373435623533646263363335303237
61303065326662396532653339653730396562313637616166343466376137626236396137343563
35626165313930316562393737626537366430373464646339653534383361313539326332376231
65633961623435373138646562633233333165323232653236643762303138393731623338643132
65643437373838653831346264373738373332353733646133633361333861633464343239366531
34663839383731373733313964373532613663663461353663653332333433333736643161363530
30626363353466346164306436353561656137356363373565636661346232623330303633623331
37613539326664616134363930396266393736333630306537303532373435633362616232396338
61666132393466633730326432363265313938376639623462306339306633303433653034343438
62333361653037633461393234383433643531323531326137356462643964353266663966326338
39393062613834646666303638363532303530333338663037363431636166353832303731336438
32346430393561616437366162666233353164383231643331623063353335626231643761643764
36366665323866643639356337616237646166626261623530353965653135333433643834326439
63376466646263346637326631396439346464616462363238396433313339656262636331393635
316437373434363537346461303732316334
